[package]
name = "smart_solar_grid"
version = "0.1.0"
edition = "2021"
authors = ["SolarGridX Team"]
description = "A blockchain-based P2P energy trading platform"

[dependencies]
# Core dependencies

[workspace]
resolver = "2"
members = [
    "pallets/energy-token",
    "pallets/energy-trade",
    "pallets/energy-transfer",
    "pallets/payment-settlement",
    "pallets/price-discovery",
    "node",
    "runtime",
]