[package]
name = "smart_solar_grid"
version = "0.1.0"
edition = "2021"
authors = ["SolarGridX Team"]
description = "A blockchain-based P2P energy trading platform"

[dependencies]
# Core dependencies
parity-scale-codec = { version = "3.6.9", features = ["derive"] }
frame-support = "38.0.0"
frame-system = "38.0.0"
sp-runtime = "39.0.3"
sp-core = "28.0.0"
sp-std = "14.0.0"
sp-io = "38.0.0"
sp-version = "37.0.0"

# Async runtime
tokio = { version = "1.35", features = ["full"] }
async-trait = "0.1.77"

# Serialization
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"

# Cryptography
sha2 = "0.10.8"
hex = "0.4.3"

parity-util-mem = "0.12.0"

[workspace]
resolver = "2"
members = [
    "pallets/energy-token",
    "pallets/energy-trade",
    "pallets/energy-transfer",
    "pallets/payment-settlement",
    "pallets/price-discovery",
    "node",
    "runtime",
]