[package]
name = "smart_solar_grid"
version = "0.1.0"
edition = "2021"
authors = ["SolarGridX Team"]
description = "A blockchain-based P2P energy trading platform"

[dependencies]
# Core dependencies
parity-scale-codec = { version = "3.2.2", features = ["derive"] }
frame-support = "6.0.0"
frame-system = "6.0.0"
sp-runtime = "6.0.0"
sp-core = "6.0.0"
sp-std = "6.0.0"
sp-io = "6.0.0"
sp-version = "6.0.0"

# Async runtime
tokio = { version = "1.28", features = ["full"] }
async-trait = "0.1.68"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Cryptography
sha2 = "0.10"
hex = "0.4"

# Add this to force all dependencies to use the same version
parity-util-mem = "0.11.0"

[workspace]
resolver = "2"
members = [
    "pallets/energy-token",
    "pallets/energy-trade",
    "pallets/energy-transfer",
    "pallets/payment-settlement",
    "pallets/price-discovery",
    "node",
    "runtime",
]