[package]
name = "pallet-payment-settlement"
version = "0.1.0"
edition = "2021"
authors = ["SolarGridX Team"]

[dependencies]
frame-support = { version = "38.0.0", default-features = false }
frame-system = { version = "38.0.0", default-features = false }
